name: Build Dev

on:
  push:
    branches: [ develop ]
    paths: 
      - 'SiraUI/**'
      - '.github/workflows/develop.yml'
  pull_request:
    branches: [ develop ]
    paths:  
      - 'SiraUI/**'
      - '.github/workflows/develop.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: SiraRef
      env:
        FILES_URL: ${{ secrets.SDEPS_URL }}
      run: wget --no-check-certificate "$FILES_URL" -q -O xfs.zip
    - name: ExtractSiraRef
      run: unzip -q -n xfs.zip -d ./Refs
    - name: Build
      id: Build
      env: 
        FrameworkPathOverride: /usr/lib/mono/4.7.2-api
      run: dotnet build --configuration Debug
